server:
  port: 8080
servlet:
  context-path: /Digital_Study_Resource
#
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/TrialDB"
    username: quannt18 #replace by local username
    password: 123456 #replace by local password
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
